### ISSUE TITLE
unable to implement in react native 0.67

### ISSUE THREAD

**Issue by gowthambalashanmugam** [TechStark/opencv-js#18]
Facing below error when i tried to implement it, Can anyone help us to sort it out?

error: RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at tokenize (/Users/comp/work/mobile-app/react-mob-app/node_modules/@babel/highlight/lib/index.js:67:38)
    at tokenize.next (<anonymous>)
    at highlightTokens (/Users/comp/work/mobile-app/react-mob-app/node_modules/@babel/highlight/lib/index.js:84:3)
    at highlight (/Users/comp/work/mobile-app/react-mob-app/node_modules/@babel/highlight/lib/index.js:112:12)
    at codeFrameColumns (/Users/comp/work/mobile-app/react-mob-app/node_modules/@babel/code-frame/lib/index.js:103:65)
    at UnableToResolveError.buildCodeFrameMessage (/Users/comp/work/mobile-app/react-mob-app/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:264:12)
    at new UnableToResolveError (/Users/comp/work/mobile-app/react-mob-app/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:223:35)
    at ModuleResolver.resolveDependency (/Users/comp/work/mobile-app/react-mob-app/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:129:15)
    at DependencyGraph.resolveDependency (/Users/comp/work/mobile-app/react-mob-app/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/node-haste/DependencyGraph.js:288:43)

**Comment by FabledWeb** [comment]
I get the same error. I've attempted a few things: none of which have helped.

1. switched from trying it in an Expo-based project to a normal ReactNative project.
2. Tried only importing the methods I need (starting with `import {imread} from '@techstark/opencv-js';`) and even just including that single function causes the same problem.

**Comment by gowthambalashanmugam** [comment]
I couldn't resolve that, else we can integrate OpenCV 3.4.1 as a native plugin which causes more weightage of the app but no option.

**Comment by pepperav** [comment]
`error: RangeError: Maximum call stack size exceeded`

I get this error too on react-native 0.71.8 and expo ~48.0.15.

Any solutions?

**Comment by thanhnv2303** [comment]
I have the same issue

**Comment by gameveloster** [comment]
Is this solved after 2 years? Getting the same error using
- `expo@51.0.13` 
- `react-native@0.74.2`
- `@techstark/opencv-js@4.9.0-release.3`

**Comment by el-fuego** [comment]
I have the same issue and idea for the fix: can it be solved by exposing all the functions in **separate files** (eg. /src/*) to the package? 
To have the ability to import them separately instead of 1 large file.
