### ISSUE TITLE
ES Module (ESM) import compatibility

### ISSUE THREAD

**Issue by AronRubin** [TechStark/opencv-js#44]
I need this patch script in my package.json to have opencv-js work with import in the browser (testing on Edge).

```json
  "scripts": {
    ...
    "fix-opencv-import": "replace \"if[(]typeof window==='object'[)][{]root.cv=factory[(][)];[}]\" \"if(typeof window==='object'){window.cv=factory();}\" node_modules/@techstark/opencv-js/dist/opencv.js",
    ...
  },
```

Thank you

**Comment by kkudlak45** [comment]
I just ran into this issue as well while trying to write tests with `@web/test-runner`

Looking at the opencv.js bundle

```
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(function () {
      return (root.cv = factory());
    });
  } else if (typeof module === 'object' && module.exports) {
    // Node. Does not work with strict CommonJS, but
    // only CommonJS-like environments that support module.exports,
    // like Node.
    module.exports = factory();
  } else if (typeof window === 'object') {
    // Browser globals
    root.cv = factory();
  } else if (typeof importScripts === 'function') {
    // Web worker
    root.cv = factory();
  } else {
    // Other shells, e.g. d8
    root.cv = factory();
  }
}(this, function () {
```

The line `else if (typeof window === 'object')` I think is meant to detect whenever opencv.js is running in a browser. In this case, I think `root` is meant to be a reference to the browser's `window` object. i.e. `root.cv = factory()` should functionally be the same as `window.cv = factory()`. But, since root is undefined, you get:

```
TypeError: Cannot set properties of undefined (setting 'cv')
        at node_modules/@techstark/opencv-js/dist/opencv.js:14:13
        at node_modules/@techstark/opencv-js/dist/opencv.js:22:2
```

I fixed this on my end by replacing `}(this, function () {` on line 22 with `}(globalThis, function () {`.  The`globalThis` variable in my case was referencing the window as expected while `this` was undefined.

This seems like an issue with [opencv.js](https://docs.opencv.org/4.10.0/opencv.js) itself to me
