### ISSUE TITLE
TypeError: cv2.Mat is not a constructor

### ISSUE THREAD

**Issue by xWalian** [TechStark/opencv-js#67]
While using @techstark/opencv-js on newest angular version 17.3.3 and with typescript 5.4.4 it fails to use cv.Mat anymore. On older versions of typescript and angular it is possible to use it

**Comment by ttt43ttt** [comment]
what's the error? do you have an online code example?

**Comment by xWalian** [comment]
i don't have code online but i provide you a simple code to better understanding
 `
        console.log(cv)
        const img = cv.imread(imgElement);
        setTimeout(()=>{
          let test = new cv.Mat();
          console.log(test)

        }, 10000)

        let grayImage = new cv.Mat();
        const mat = new cv.Mat(img.rows, img.cols, img.type());
        mat.setTo(new cv.Scalar(255, 255, 255, 255));
`
cv.imread works fine and imgElement is loaded i can without errors print it

console log shows diffrent objects depends on version of angular most in newer version disappeared,

when i'm trying to make new cv.Mat() error looks like this 
`TypeError: cv2.Mat is not a constructor
    at _PdfVieverPage.<anonymous> (pdf-viever.page.ts:339:25)
    at Generator.next (<anonymous>)
    at fulfilled (main.js:24:24)
    at _ZoneDelegate.invoke (zone.js:365:28)
    at Object.onInvoke (core.mjs:14882:33)
    at _ZoneDelegate.invoke (zone.js:364:34)
    at _ZoneImpl.run (zone.js:111:43)
    at zone.js:2447:40
    at _ZoneDelegate.invokeTask (zone.js:398:33)
    at core.mjs:14556:55`

**Comment by xWalian** [comment]
this is also my package.json
```
{
	"name": "signa",
	"version": "0.30.1-1",
	"private": true,
	"dependencies": {
		"@angular/animations": "^17.3.3",
		"@angular/cdk": "^17.3.3",
		"@angular/common": "^17.3.3",
		"@angular/compiler": "^17.3.3",
		"@angular/core": "^17.3.3",
		"@angular/forms": "^17.3.3",
		"@angular/platform-browser": "^17.3.3",
		"@angular/platform-browser-dynamic": "^17.3.3",
		"@angular/router": "^17.3.3",
		"@techstark/opencv-js": "^4.9.0-release.3",
		"@tensorflow/tfjs": "^4.20.0",
		"bignumber.js": "^9.1.2",
		"chart.js": "^4.4.2",
		"core-js": "^3.37.1",
		"file-saver": "^2.0.5",
		"image-js": "^0.35.5",
		"jinx": "^0.1.2",
		"pdfjs-dist": "^3.11.174",
		"rxjs": "~7.8.1",
		"socket.io-client": "^4.7.5",
		"tesseract.js": "^5.1.0",
		"tiff": "^6.1.0",
		"tslib": "^2.6.2",
		"uuid": "^9.0.1",
		"zone.js": "~0.14.4"
	},
	"devDependencies": {
		"@angular-devkit/build-angular": "^17.3.3",
		"@angular-eslint/eslint-plugin": "^17.3.0",
		"@angular-eslint/eslint-plugin-template": "^17.3.0",
		"@angular-eslint/template-parser": "^17.3.0",
		"@angular/cli": "^17.3.3",
		"@angular/compiler-cli": "^17.3.3",
		"@angular/localize": "^17.3.3",
		"@commitlint/cli": "^19.2.1",
		"@commitlint/config-conventional": "^19.1.0",
		"@openapitools/openapi-generator-cli": "^2.13.1",
		"@playwright/test": "^1.43.0",
		"@types/chart.js": "^2.9.41",
		"@types/file-saver": "^2.0.7",
		"@types/jasmine": "~5.1.4",
		"@types/node": "^20.11.17",
		"@types/uuid": "^9.0.8",
		"@typescript-eslint/eslint-plugin": "^7.5.0",
		"@typescript-eslint/parser": "^7.5.0",
		"commitlint": "^19.2.1",
		"eslint": "^8.57.0",
		"eslint-config-prettier": "^9.1.0",
		"eslint-plugin-prettier": "^5.1.3",
		"husky": "^9.0.11",
		"jasmine-core": "~5.1.2",
		"karma": "~6.4.3",
		"karma-chrome-launcher": "~3.2.0",
		"karma-coverage": "~2.2.1",
		"karma-jasmine": "~5.1.0",
		"karma-jasmine-html-reporter": "~2.1.0",
		"lint-staged": "^15.2.2",
		"playwright": "^1.43.0",
		"prettier": "^3.2.5",
		"stylelint": "^16.3.1",
		"stylelint-config-standard": "^36.0.0",
		"stylelint-config-standard-scss": "^13.1.0",
		"typescript": "~5.4.4"
	}
}
```
and tsconfig.json
```
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
	"compileOnSave": false,
	"compilerOptions": {
		"outDir": "./dist/out-tsc",
		"forceConsistentCasingInFileNames": true,
		"strict": true,
		"noImplicitOverride": true,
		"noPropertyAccessFromIndexSignature": true,
		"noImplicitReturns": true,
		"noFallthroughCasesInSwitch": true,
		"skipLibCheck": true,
		"esModuleInterop": true,
		"sourceMap": true,
		"declaration": false,
		"experimentalDecorators": true,
		"moduleResolution": "node",
		"importHelpers": true,
		"target": "ES2022",
		"module": "ES2022",
		"useDefineForClassFields": false,
		"lib": ["ES2022", "dom"],
		"paths": {
			"@config": ["./config/config.ts"],
			"@app/*": ["./app/src/*"],
			"@core/*": ["./libs/core/src/lib/*"],
			"@erp/*": ["./libs/erp/src/lib/*"]
		}
	},
	"angularCompilerOptions": {
		"enableI18nLegacyMessageIdFormat": false,
		"strictInjectionParameters": true,
		"strictInputAccessModifiers": true,
		"strictTemplates": true
	}
}

```

**Comment by xWalian** [comment]
ok i found issue problem was with import correct should be import cv from '@techstark/opencv-js'

**Comment by tugushka** [comment]
> ok i found issue problem was with import correct should be import cv from '@techstark/opencv-js'

Can someone explain why this happened? It fixed my issue too.
